//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbom.Data.IdentityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInvitedDiscount
    {
        public string UserId { get; set; }
        public int DiscountId { get; set; }
        public int Amount { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Discount Discount { get; set; }
    }
}
