//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbom.Data.IdentityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCommunication
    {
        public int CommunicationId { get; set; }
        public string UserId { get; set; }
        public string Value { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Communicatio Communicatio { get; set; }
    }
}
