declare var newUsersJsonUsers: string;
declare var userLineJsonUsers: string; 
declare var upgradeRoelUsers: string; 
declare var upgradeRoelFirmUsers: string; 
declare var setWatchRoleUsers: string; 
declare var moveUserUsers: string; 
declare var getUserInfoJsonUsers: string; 
declare var setUsersFootUsers: string; 
declare var getTreeUsersJsonUsers: string; 