//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbom.Data.ContentModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContentDbEntities : DbContext
    {
        public ContentDbEntities()
            : base("name=ContentDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessToEventType> AccessToEventTypes { get; set; }
        public virtual DbSet<AccessToMenu> AccessToMenus { get; set; }
        public virtual DbSet<DefaultSettingsValue> DefaultSettingsValues { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventSpiker> EventSpikers { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<ExtraRegParam> ExtraRegParams { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<PostType> PostTypes { get; set; }
        public virtual DbSet<ReceivedExtraRegParam> ReceivedExtraRegParams { get; set; }
        public virtual DbSet<Registrator> Registrators { get; set; }
        public virtual DbSet<RegistratorSetting> RegistratorSettings { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaskToDo> TaskToDoes { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<UserComplitedTask> UserComplitedTasks { get; set; }
        public virtual DbSet<UserExtraRegParam> UserExtraRegParams { get; set; }
        public virtual DbSet<UsersTemplateSetting> UsersTemplateSettings { get; set; }
    }
}
