//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbom.Data.ContentModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public System.DateTime Date { get; set; }
        public string Text { get; set; }
        public string Title { get; set; }
        public int TypeId { get; set; }
    
        public virtual PostType PostType { get; set; }
    }
}
